base_images:
  cli:
    name: "4.19"
    namespace: ocp
    tag: cli
  openshift-virtualization-tests:
    name: openshift-virtualization-tests
    namespace: ci
    tag: cnv-4.19
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: cnv-odf-tests-aws-ipi-ocp419-gs-baremetal
  cron: 0 23 31 2 *
  steps:
    cluster_profile: metal-redhat-gs
    env:
      KCFG_SRC_SFX: dfrazzet--test1
    test:
    - ref: interop-tests-cnv-tests-gs-baremetal-localnet
    workflow: external-cluster
  timeout: 6h0m0s
zz_generated_metadata:
  branch: master
  org: RedHatQE
  repo: interop-testing
  variant: cnv-odf-ocp4.19-lp-gs_baremetal
