base_images:
  cli:
    name: "4.19"
    namespace: ocp
    tag: cli
  ocs-ci-tests:
    name: ocs-ci-container
    namespace: ci
    tag: stable
  openshift-virtualization-tests:
    name: openshift-virtualization-tests
    namespace: ci
    tag: cnv-4.19
build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: golang-1.21
images:
- build_args:
  - name: OCP_VERSION
    value: "4.19"
  - name: OC_CLI_VERSION
    value: latest
  context_dir: cnv-ci
  dockerfile_path: Dockerfile
  to: cnv-ci
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.19"
resources:
  '*':
    requests:
      cpu: 200m
      memory: 400Mi
tests:
- as: cnv-odf-tests-aws-ipi-ocp419-gs-baremetal
  cron: 0 23 31 2 *
  steps:
    cluster_profile: metal-redhat-gs
    env:
      KCFG_SRC_SFX: <userID>--<freeDescription>
    test:
    - chain: cucushift-installer-check-cluster-health
    - ref: interop-tests-deploy-odf
    - ref: interop-tests-ocs-tests
    - ref: interop-tests-cnv-tests-e2e-deploy
    - ref: interop-tests-openshift-virtualization-tests
    workflow: external-cluster
  timeout: 6h0m0s
zz_generated_metadata:
  branch: master
  org: RedHatQE
  repo: interop-testing
  variant: cnv-odf-ocp4.19-lp-gs_baremetal
